name: build-docs

on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.6
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install -r docs/requirements.txt
        pip install .[all]
    - name: Build Documentation
      shell: bash -l {0}
      run: make build-docs

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: './docs/build/html'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        enable-commit-comment: false
        alias: kornia
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}